MIN_ROI_PIXELS = 50

AB_BIN_WIDTH = 8.0
AB_PEAK_THRESHOLD = 0.05
AB_MERGE_DIST = 15.0

EFFECTIVE_CLUSTER_MIN_RATIO = 0.02

MAIN_RATIO_PURE_MIN = 0.80
SECOND_RATIO_PURE_MAX = 0.10
MINOR_TOTAL_PURE_MAX = 0.20
MULTI_SMALL_COLORS_MIN_COUNT = 3
MULTI_SMALL_COLORS_MINOR_TOTAL_MIN = 0.15

NEUTRAL_CHROMA_MAX = 12.0
NEUTRAL_REGION_RATIO_MIN = 0.60
L_HIST_BINS = 50
L_PEAK_MIN_RATIO = 0.10
L_PEAK_MIN_DELTA = 30.0
L_MINOR_TOTAL_MIN = 0.20
